name: SSTube Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Build executable with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile --windowed SStube.py

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
         name: SSTube-executable
         path: dist/SSTube.exe

